// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAknjEQhacYbf7w2WhRgqG4IPIQtEEqzFE',
    appId: '1:905655696107:web:945b1d344019ecaa3fdcae',
    messagingSenderId: '905655696107',
    projectId: 'controledeestoque01-c4a45',
    authDomain: 'controledeestoque01-c4a45.firebaseapp.com',
    storageBucket: 'controledeestoque01-c4a45.appspot.com',
    measurementId: 'G-X5XQ825T3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBippPR4M8k1_5eyGMwohaiYac78yEsMZs',
    appId: '1:905655696107:android:9d0ed839dabde85a3fdcae',
    messagingSenderId: '905655696107',
    projectId: 'controledeestoque01-c4a45',
    storageBucket: 'controledeestoque01-c4a45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB76iZMqL3sP7J2RgXxoQp9EIFQVgkX9v4',
    appId: '1:905655696107:ios:df292d04d2150ae53fdcae',
    messagingSenderId: '905655696107',
    projectId: 'controledeestoque01-c4a45',
    storageBucket: 'controledeestoque01-c4a45.appspot.com',
    iosBundleId: 'com.example.controleDeEstoque',
  );
}
